basic:
  url: "https://www.xiaocoder.com"
  host: "0.0.0.0"
  port: 8080
  mode: "debug"
  online_time: "2021-05-20 13:14:00"

auth:
  jwt_expire: 86400
  jwt_secret: "JWT"

logger:
  level: "info"
  directory: "./logs"
  rotation_time: 24
  rotation_count: 7

pager:
  limit: 10
  offset: 0

rds:
  driver_name: "mysql"
  debug: true
  mysql:
    host: "127.0.0.1"
    port: 3306
    username: "root"
    password: "123456"
    database: "database"
  postgresql:
    host: "127.0.0.1"
    port: 5432
    username: "root"
    password: "123456"
    database: "database"
  max_idle_conns: 20
  max_open_conns: 200
  conn_max_lifetime: 1

cache:
  driver_name: "redis"
  redis:
    host: "127.0.0.1"
    port: "6379"
    password: ""
    db: 0
    pool_size: 100
